## Python DA Assignment 1—Numpy and Pandas ##
### Data analysis using NumPy and Pandas ###

In [2]:
# Numpy Array Operations:
# 1. Create a 1D NumPy Array:
import numpy as np
import pandas as pd
temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

In [3]:
# 2. Inspection and Properties:
print("Shape:", temperatures_w1.shape)
print("Data type:", temperatures_w1.dtype)
print("Number of elements:", temperatures_w1.size)

Shape: (7,)
Data type: float64
Number of elements: 7

In [4]:
# 3. Array Operations:
temperatures_f1 = (temperatures_w1 * 9/5) + 32

print("Temperatures in Fahrenheit:", temperatures_f1)
print("Maximum temperature :", temperatures_w1.max())
print("Minimum temperature :", temperatures_w1.min())
print("Mean temperature :", temperatures_w1.mean())

Temperatures in Fahrenheit: [72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Maximum temperature : 26.1
Minimum temperature : 20.8
Mean temperature : 23.542857142857144

In [5]:
# 4. Array Slicing and Indexing:

print("First three days:", temperatures_w1[:3])
print("Weekend:", temperatures_w1[-2:])
print("Middle three days:", temperatures_w1[2:5])

First three days: [22.5 25.3 20.8]
Weekend: [24.8 21.9]
Middle three days: [20.8 23.4 26.1]

In [6]:
# 5. Create a 2D Array:
temperatures = np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])

print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]

In [7]:
# 6. Inspect and Slice the 2D Array:

print("Shape:", temperatures.shape)
print("Data type:", temperatures.dtype)
print("Total number of elements:", temperatures.size)

print("Week 1:", temperatures[0])
print("Week 2:", temperatures[1])
print("Week 1 weekend:", temperatures[0, -2:])
print("Week 2 weekend:", temperatures[1, -2:])

Shape: (2, 7)
Data type: float64
Total number of elements: 14
Week 1: [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
Week 2: [19.2 22.5 21.3 24.  23.5 22.8 20.1]
Week 1 weekend: [24.8 21.9]
Week 2 weekend: [22.8 20.1]

In [8]:
# Pandas Series:
# 1. Creating Pandas Series:
# Create a Pandas Series named marks with the following data:
# Marks: 95, 92, 89, 85, 80
# Custom Indices: 'Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'

marks = pd.Series([95, 92, 89, 85, 80],index=["Rank1", "Rank2", "Rank3", "Rank4", "Rank5"],name="marks")
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
Name: marks, dtype: int64

In [9]:
# 2. Indexing and Slicing:
# Use the integer index position to access the mark of the 1st rank student.
print(marks.iloc[0])

# Use the loc accessor to retrieve the marks of the top 3 ranks by specifying their index
#labels.
print(marks.loc[["Rank1", "Rank2", "Rank3"]])

# Use the iloc accessor to retrieve the mark of the 3rd-ranked student.
print(marks.iloc[2])

# Apply a boolean mask to filter the Series and retrieve the ranks where the marks are
#greater than 90.
print(marks[marks > 90])

95
Rank1    95
Rank2    92
Rank3    89
Name: marks, dtype: int64
89
Rank1    95
Rank2    92
Name: marks, dtype: int64

In [10]:
# 3. Manipulating Series:
# Modify the mark of the student with the 1st rank to 100.
marks.loc["Rank1"] = 100


# Remove the entry corresponding to the last rank from the Series.
marks = marks.drop("Rank5")


# Compute the CGPA by dividing each mark in the Series by 10.
cgpa = marks / 10
print(marks)
print(cgpa)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Name: marks, dtype: int64
Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
Name: marks, dtype: float64

In [11]:
# Pandas DataFrame:
# Creating Pandas DataFrame:

transactions = pd.DataFrame({"TransactionID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
                             "ProductCategory": ["Electronics","Clothing","Electronics","Furniture","Clothing","Electronics",
                                                 "Furniture","Clothing","Furniture","Electronics"],
                             "Region": ["North","South","North","East","West","North","East","West","South","North"],
                             "Amount": [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]})

transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [12]:
# 2. Data Exploration:

print("First 5 rows:")
display(transactions.head())

print("Last 5 rows:")
display(transactions.tail())

print("Shape:", transactions.shape)
print("Column names:", transactions.columns.tolist())

print("Data types:")
print(transactions.dtypes)

print("Basic information:")
transactions.info()

First 5 rows:

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

Last 5 rows:

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

Shape: (10, 4)
Column names: ['TransactionID', 'ProductCategory', 'Region', 'Amount']
Data types:
TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object
Basic information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    10 non-null     int64
 1   ProductCategory  10 non-null     object
 2   Region           10 non-null     object
 3   Amount           10 non-null     int64
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes

In [13]:
# 3. Manipulating the DataFrame:
# Modify Amount for TransactionID 102 to 165
transactions.loc[
    transactions['TransactionID'] == 102,
    'Amount'
] = 165

print("\nAfter changing TransactionID 102 Amount to 165:")
print(transactions)


# Add Discount column = 10% of Amount
transactions['Discount'] = transactions['Amount'] * 0.10

print("\nAfter adding Discount column:")
print(transactions)


# Remove TransactionID 109
transactions = transactions[
    transactions['TransactionID'] != 109
].reset_index(drop=True)

print("\nAfter removing TransactionID 109:")
print(transactions)


# Delete Discount column
transactions = transactions.drop(columns=['Discount'])

print("\nAfter deleting Discount column:")
print(transactions)

After changing TransactionID 102 Amount to 165:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

After adding Discount column:
   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

After removing TransactionID 109:
   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            110     Electronics  North     400      40.0

After deleting Discount column:
   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            110     Electronics  North     400